# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"lowest_color": "00_ndpretty.ipynb",
         "highest_color": "00_ndpretty.ipynb",
         "number_format": "00_ndpretty.ipynb",
         "default_max_dim_size": "00_ndpretty.ipynb",
         "ndarray_html": "00_ndpretty.ipynb",
         "register_formatter": "00_ndpretty.ipynb",
         "ndarray_stats_print_formatter": "00_ndpretty.ipynb",
         "no_print_formatter": "00_ndpretty.ipynb",
         "register_ndarray_formatter": "00_ndpretty.ipynb",
         "torch_tensor_html": "00_ndpretty.ipynb",
         "tensor_stats_print_formatter": "00_ndpretty.ipynb",
         "register_torch_tensor_formatter": "00_ndpretty.ipynb",
         "default": "00_ndpretty.ipynb"}

modules = ["core.py"]

doc_url = "https://deutschmn.github.io/ndpretty/"

git_url = "https://github.com/deutschmn/ndpretty/tree/master/"

def custom_doc_links(name): return None
